version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
  # target removed; single-stage Dockerfile
    container_name: lumenslate-web
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - ENV=production
    depends_on:
      - redis
      - async
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  async:
    build:
      context: .
      dockerfile: Dockerfile
  # target removed; single-stage Dockerfile
    container_name: lumenslate-async
    command: ["go", "run", "main.go", "--async-only"]
    environment:
      - PORT=8090
      - REDIS_ADDR=redis:6379
      - ENV=production
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    image: redis:7.2-alpine
    container_name: lumenslate-redis
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: lumenslate-asynqmon
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8100:8080"
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8100"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  redis_data: