version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumenslate-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
