// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/ai_service.proto

package ai_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- /context_generator.py ---
type GenerateContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Keywords      []string               `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContextRequest) Reset() {
	*x = GenerateContextRequest{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContextRequest) ProtoMessage() {}

func (x *GenerateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContextRequest.ProtoReflect.Descriptor instead.
func (*GenerateContextRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateContextRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GenerateContextRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *GenerateContextRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GenerateContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContextResponse) Reset() {
	*x = GenerateContextResponse{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContextResponse) ProtoMessage() {}

func (x *GenerateContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContextResponse.ProtoReflect.Descriptor instead.
func (*GenerateContextResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateContextResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// --- /variable_detector.py ---
type VariableDetectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableDetectorRequest) Reset() {
	*x = VariableDetectorRequest{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableDetectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableDetectorRequest) ProtoMessage() {}

func (x *VariableDetectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableDetectorRequest.ProtoReflect.Descriptor instead.
func (*VariableDetectorRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *VariableDetectorRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type VariableDetectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []*DetectedVariable    `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableDetectorResponse) Reset() {
	*x = VariableDetectorResponse{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableDetectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableDetectorResponse) ProtoMessage() {}

func (x *VariableDetectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableDetectorResponse.ProtoReflect.Descriptor instead.
func (*VariableDetectorResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *VariableDetectorResponse) GetVariables() []*DetectedVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type DetectedVariable struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value          string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	NamePositions  []int32                `protobuf:"varint,3,rep,packed,name=namePositions,proto3" json:"namePositions,omitempty"`
	ValuePositions []int32                `protobuf:"varint,4,rep,packed,name=valuePositions,proto3" json:"valuePositions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectedVariable) Reset() {
	*x = DetectedVariable{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedVariable) ProtoMessage() {}

func (x *DetectedVariable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedVariable.ProtoReflect.Descriptor instead.
func (*DetectedVariable) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *DetectedVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetectedVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DetectedVariable) GetNamePositions() []int32 {
	if x != nil {
		return x.NamePositions
	}
	return nil
}

func (x *DetectedVariable) GetValuePositions() []int32 {
	if x != nil {
		return x.ValuePositions
	}
	return nil
}

// --- /question_segmentation.py ---
type QuestionSegmentationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionSegmentationRequest) Reset() {
	*x = QuestionSegmentationRequest{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionSegmentationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionSegmentationRequest) ProtoMessage() {}

func (x *QuestionSegmentationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionSegmentationRequest.ProtoReflect.Descriptor instead.
func (*QuestionSegmentationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *QuestionSegmentationRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type QuestionSegmentationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SegmentedQuestion string                 `protobuf:"bytes,1,opt,name=segmentedQuestion,proto3" json:"segmentedQuestion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuestionSegmentationResponse) Reset() {
	*x = QuestionSegmentationResponse{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionSegmentationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionSegmentationResponse) ProtoMessage() {}

func (x *QuestionSegmentationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionSegmentationResponse.ProtoReflect.Descriptor instead.
func (*QuestionSegmentationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionSegmentationResponse) GetSegmentedQuestion() string {
	if x != nil {
		return x.SegmentedQuestion
	}
	return ""
}

// --- /mcq_variation_generator.py ---
type MCQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	AnswerIndex   int32                  `protobuf:"varint,3,opt,name=answerIndex,proto3" json:"answerIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCQRequest) Reset() {
	*x = MCQRequest{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCQRequest) ProtoMessage() {}

func (x *MCQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCQRequest.ProtoReflect.Descriptor instead.
func (*MCQRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *MCQRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MCQRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MCQRequest) GetAnswerIndex() int32 {
	if x != nil {
		return x.AnswerIndex
	}
	return 0
}

type MCQVariation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variations    []*MCQQuestion         `protobuf:"bytes,1,rep,name=variations,proto3" json:"variations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCQVariation) Reset() {
	*x = MCQVariation{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCQVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCQVariation) ProtoMessage() {}

func (x *MCQVariation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCQVariation.ProtoReflect.Descriptor instead.
func (*MCQVariation) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *MCQVariation) GetVariations() []*MCQQuestion {
	if x != nil {
		return x.Variations
	}
	return nil
}

type MCQQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	AnswerIndex   int32                  `protobuf:"varint,3,opt,name=answerIndex,proto3" json:"answerIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCQQuestion) Reset() {
	*x = MCQQuestion{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCQQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCQQuestion) ProtoMessage() {}

func (x *MCQQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCQQuestion.ProtoReflect.Descriptor instead.
func (*MCQQuestion) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *MCQQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MCQQuestion) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MCQQuestion) GetAnswerIndex() int32 {
	if x != nil {
		return x.AnswerIndex
	}
	return 0
}

// --- /msq_variation_generator.py ---
type MSQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	AnswerIndices []int32                `protobuf:"varint,3,rep,packed,name=answerIndices,proto3" json:"answerIndices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSQRequest) Reset() {
	*x = MSQRequest{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSQRequest) ProtoMessage() {}

func (x *MSQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSQRequest.ProtoReflect.Descriptor instead.
func (*MSQRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *MSQRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MSQRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MSQRequest) GetAnswerIndices() []int32 {
	if x != nil {
		return x.AnswerIndices
	}
	return nil
}

type MSQVariation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variations    []*MSQQuestion         `protobuf:"bytes,1,rep,name=variations,proto3" json:"variations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSQVariation) Reset() {
	*x = MSQVariation{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSQVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSQVariation) ProtoMessage() {}

func (x *MSQVariation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSQVariation.ProtoReflect.Descriptor instead.
func (*MSQVariation) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *MSQVariation) GetVariations() []*MSQQuestion {
	if x != nil {
		return x.Variations
	}
	return nil
}

type MSQQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	AnswerIndices []int32                `protobuf:"varint,3,rep,packed,name=answerIndices,proto3" json:"answerIndices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSQQuestion) Reset() {
	*x = MSQQuestion{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSQQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSQQuestion) ProtoMessage() {}

func (x *MSQQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSQQuestion.ProtoReflect.Descriptor instead.
func (*MSQQuestion) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *MSQQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MSQQuestion) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MSQQuestion) GetAnswerIndices() []int32 {
	if x != nil {
		return x.AnswerIndices
	}
	return nil
}

// --- /variable_randomizer.py ---
type FilterAndRandomizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	UserPrompt    string                 `protobuf:"bytes,2,opt,name=userPrompt,proto3" json:"userPrompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterAndRandomizerRequest) Reset() {
	*x = FilterAndRandomizerRequest{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterAndRandomizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAndRandomizerRequest) ProtoMessage() {}

func (x *FilterAndRandomizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAndRandomizerRequest.ProtoReflect.Descriptor instead.
func (*FilterAndRandomizerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *FilterAndRandomizerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *FilterAndRandomizerRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

type FilterAndRandomizerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []*RandomizedVariable  `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterAndRandomizerResponse) Reset() {
	*x = FilterAndRandomizerResponse{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterAndRandomizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAndRandomizerResponse) ProtoMessage() {}

func (x *FilterAndRandomizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAndRandomizerResponse.ProtoReflect.Descriptor instead.
func (*FilterAndRandomizerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{14}
}

func (x *FilterAndRandomizerResponse) GetVariables() []*RandomizedVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type RandomizedVariable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value can be int or string, so use string for proto3
	Value         string          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Filters       *VariableFilter `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomizedVariable) Reset() {
	*x = RandomizedVariable{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomizedVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomizedVariable) ProtoMessage() {}

func (x *RandomizedVariable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomizedVariable.ProtoReflect.Descriptor instead.
func (*RandomizedVariable) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{15}
}

func (x *RandomizedVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RandomizedVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RandomizedVariable) GetFilters() *VariableFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type VariableFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         []int32                `protobuf:"varint,1,rep,packed,name=range,proto3" json:"range,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableFilter) Reset() {
	*x = VariableFilter{}
	mi := &file_internal_proto_ai_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableFilter) ProtoMessage() {}

func (x *VariableFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_ai_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableFilter.ProtoReflect.Descriptor instead.
func (*VariableFilter) Descriptor() ([]byte, []int) {
	return file_internal_proto_ai_service_proto_rawDescGZIP(), []int{16}
}

func (x *VariableFilter) GetRange() []int32 {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *VariableFilter) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_internal_proto_ai_service_proto protoreflect.FileDescriptor

const file_internal_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/ai_service.proto\x12\n" +
	"ai_service\"l\n" +
	"\x16GenerateContextRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1a\n" +
	"\bkeywords\x18\x02 \x03(\tR\bkeywords\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"3\n" +
	"\x17GenerateContextResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"5\n" +
	"\x17VariableDetectorRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"V\n" +
	"\x18VariableDetectorResponse\x12:\n" +
	"\tvariables\x18\x01 \x03(\v2\x1c.ai_service.DetectedVariableR\tvariables\"\x8a\x01\n" +
	"\x10DetectedVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12$\n" +
	"\rnamePositions\x18\x03 \x03(\x05R\rnamePositions\x12&\n" +
	"\x0evaluePositions\x18\x04 \x03(\x05R\x0evaluePositions\"9\n" +
	"\x1bQuestionSegmentationRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"L\n" +
	"\x1cQuestionSegmentationResponse\x12,\n" +
	"\x11segmentedQuestion\x18\x01 \x01(\tR\x11segmentedQuestion\"d\n" +
	"\n" +
	"MCQRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12 \n" +
	"\vanswerIndex\x18\x03 \x01(\x05R\vanswerIndex\"G\n" +
	"\fMCQVariation\x127\n" +
	"\n" +
	"variations\x18\x01 \x03(\v2\x17.ai_service.MCQQuestionR\n" +
	"variations\"e\n" +
	"\vMCQQuestion\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12 \n" +
	"\vanswerIndex\x18\x03 \x01(\x05R\vanswerIndex\"h\n" +
	"\n" +
	"MSQRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12$\n" +
	"\ranswerIndices\x18\x03 \x03(\x05R\ranswerIndices\"G\n" +
	"\fMSQVariation\x127\n" +
	"\n" +
	"variations\x18\x01 \x03(\v2\x17.ai_service.MSQQuestionR\n" +
	"variations\"i\n" +
	"\vMSQQuestion\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12$\n" +
	"\ranswerIndices\x18\x03 \x03(\x05R\ranswerIndices\"X\n" +
	"\x1aFilterAndRandomizerRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1e\n" +
	"\n" +
	"userPrompt\x18\x02 \x01(\tR\n" +
	"userPrompt\"[\n" +
	"\x1bFilterAndRandomizerResponse\x12<\n" +
	"\tvariables\x18\x01 \x03(\v2\x1e.ai_service.RandomizedVariableR\tvariables\"t\n" +
	"\x12RandomizedVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x124\n" +
	"\afilters\x18\x03 \x01(\v2\x1a.ai_service.VariableFilterR\afilters\"@\n" +
	"\x0eVariableFilter\x12\x14\n" +
	"\x05range\x18\x01 \x03(\x05R\x05range\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions2\xa8\x04\n" +
	"\tAIService\x12Z\n" +
	"\x0fGenerateContext\x12\".ai_service.GenerateContextRequest\x1a#.ai_service.GenerateContextResponse\x12\\\n" +
	"\x0fDetectVariables\x12#.ai_service.VariableDetectorRequest\x1a$.ai_service.VariableDetectorResponse\x12d\n" +
	"\x0fSegmentQuestion\x12'.ai_service.QuestionSegmentationRequest\x1a(.ai_service.QuestionSegmentationResponse\x12I\n" +
	"\x15GenerateMCQVariations\x12\x16.ai_service.MCQRequest\x1a\x18.ai_service.MCQVariation\x12I\n" +
	"\x15GenerateMSQVariations\x12\x16.ai_service.MSQRequest\x1a\x18.ai_service.MSQVariation\x12e\n" +
	"\x12FilterAndRandomize\x12&.ai_service.FilterAndRandomizerRequest\x1a'.ai_service.FilterAndRandomizerResponseB&Z$internal/proto/ai_service;ai_serviceb\x06proto3"

var (
	file_internal_proto_ai_service_proto_rawDescOnce sync.Once
	file_internal_proto_ai_service_proto_rawDescData []byte
)

func file_internal_proto_ai_service_proto_rawDescGZIP() []byte {
	file_internal_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_ai_service_proto_rawDesc), len(file_internal_proto_ai_service_proto_rawDesc)))
	})
	return file_internal_proto_ai_service_proto_rawDescData
}

var file_internal_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_proto_ai_service_proto_goTypes = []any{
	(*GenerateContextRequest)(nil),       // 0: ai_service.GenerateContextRequest
	(*GenerateContextResponse)(nil),      // 1: ai_service.GenerateContextResponse
	(*VariableDetectorRequest)(nil),      // 2: ai_service.VariableDetectorRequest
	(*VariableDetectorResponse)(nil),     // 3: ai_service.VariableDetectorResponse
	(*DetectedVariable)(nil),             // 4: ai_service.DetectedVariable
	(*QuestionSegmentationRequest)(nil),  // 5: ai_service.QuestionSegmentationRequest
	(*QuestionSegmentationResponse)(nil), // 6: ai_service.QuestionSegmentationResponse
	(*MCQRequest)(nil),                   // 7: ai_service.MCQRequest
	(*MCQVariation)(nil),                 // 8: ai_service.MCQVariation
	(*MCQQuestion)(nil),                  // 9: ai_service.MCQQuestion
	(*MSQRequest)(nil),                   // 10: ai_service.MSQRequest
	(*MSQVariation)(nil),                 // 11: ai_service.MSQVariation
	(*MSQQuestion)(nil),                  // 12: ai_service.MSQQuestion
	(*FilterAndRandomizerRequest)(nil),   // 13: ai_service.FilterAndRandomizerRequest
	(*FilterAndRandomizerResponse)(nil),  // 14: ai_service.FilterAndRandomizerResponse
	(*RandomizedVariable)(nil),           // 15: ai_service.RandomizedVariable
	(*VariableFilter)(nil),               // 16: ai_service.VariableFilter
}
var file_internal_proto_ai_service_proto_depIdxs = []int32{
	4,  // 0: ai_service.VariableDetectorResponse.variables:type_name -> ai_service.DetectedVariable
	9,  // 1: ai_service.MCQVariation.variations:type_name -> ai_service.MCQQuestion
	12, // 2: ai_service.MSQVariation.variations:type_name -> ai_service.MSQQuestion
	15, // 3: ai_service.FilterAndRandomizerResponse.variables:type_name -> ai_service.RandomizedVariable
	16, // 4: ai_service.RandomizedVariable.filters:type_name -> ai_service.VariableFilter
	0,  // 5: ai_service.AIService.GenerateContext:input_type -> ai_service.GenerateContextRequest
	2,  // 6: ai_service.AIService.DetectVariables:input_type -> ai_service.VariableDetectorRequest
	5,  // 7: ai_service.AIService.SegmentQuestion:input_type -> ai_service.QuestionSegmentationRequest
	7,  // 8: ai_service.AIService.GenerateMCQVariations:input_type -> ai_service.MCQRequest
	10, // 9: ai_service.AIService.GenerateMSQVariations:input_type -> ai_service.MSQRequest
	13, // 10: ai_service.AIService.FilterAndRandomize:input_type -> ai_service.FilterAndRandomizerRequest
	1,  // 11: ai_service.AIService.GenerateContext:output_type -> ai_service.GenerateContextResponse
	3,  // 12: ai_service.AIService.DetectVariables:output_type -> ai_service.VariableDetectorResponse
	6,  // 13: ai_service.AIService.SegmentQuestion:output_type -> ai_service.QuestionSegmentationResponse
	8,  // 14: ai_service.AIService.GenerateMCQVariations:output_type -> ai_service.MCQVariation
	11, // 15: ai_service.AIService.GenerateMSQVariations:output_type -> ai_service.MSQVariation
	14, // 16: ai_service.AIService.FilterAndRandomize:output_type -> ai_service.FilterAndRandomizerResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_ai_service_proto_init() }
func file_internal_proto_ai_service_proto_init() {
	if File_internal_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_ai_service_proto_rawDesc), len(file_internal_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_ai_service_proto_msgTypes,
	}.Build()
	File_internal_proto_ai_service_proto = out.File
	file_internal_proto_ai_service_proto_goTypes = nil
	file_internal_proto_ai_service_proto_depIdxs = nil
}
